# Support the author by using the funding links below.
# Developed and maintained by: Phill (Lily-Pad) with the help of the community.
# Buy Me a Coffee: https://buymeacoffee.com/lilypad.uk

buy_me_a_coffee: lilypad.uk
# Your support means the world to me and helps my volunteering initiative Lily-Pad continue to thrive.
# Supporting my local charities, schools, and small businesses with their IT needs. From website design and hosting to consultancy and loaning equipment, everything I offer is free of charge and community-focused.
#All donations go directly towards supporting Lily-Pad — covering costs like web hosting, replacement kit, and helping more people access the technology they need.
#Your support genuinely makes a difference. Thank you!
